apiVersion: 1

datasources:
  # Prometheus
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prom:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s
      prometheusType: Prometheus
      prometheusVersion: 3.8.1
      cacheLevel: 'High'
      disableMetricsLookup: false
      incrementalQueryOverlapWindow: '10m'
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: 'jaeger'

  # Loki
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      derivedFields:
        - datasourceUid: 'jaeger'
          matcherRegex: 'trace[Ii][Dd]=([a-zA-Z0-9]+)'
          name: TraceID
          url: '/trace/$${__value.raw}'
        - datasourceUid: 'jaeger'
          matcherRegex: 'trace_id=([a-zA-Z0-9]+)'
          name: TraceID
          url: '/trace/$${__value.raw}'
      maxLines: 1000

  # Jaeger
  - name: Jaeger
    type: jaeger
    uid: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: true
    jsonData:
      nodeGraph:
        enabled: true
      tracesToLogs:
        datasourceUid: 'loki'
        filterByTraceID: true
        filterBySpanID: true
        tags: ['job', 'container', 'service', 'trace_id']
        mapTagNamesEnabled: false
      tracesToMetrics:
        datasourceUid: 'prometheus'
        tags: ['job', 'instance']
        spanStartTimeShift: '1m'
        spanEndTimeShift: '-1m'
        queries:
          - name: 'Request rate'
            query: 'sum(rate(echo_http_requests_total{service="${__tags.service}"}[5m]))'
          - name: 'Error rate'
            query: 'sum(rate(echo_http_requests_total{service="${__tags.service}", status_code=~"5.."}[5m])) / sum(rate(echo_http_requests_total{service="${__tags.service}"}[5m])) * 100'